# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: EBAC CI 
on:
    push:
        branches: [ci]
  
jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
        matrix:
        node-version: [14.x]
        
        steps:
            - uses: actions/checkout@v2
              -name: Use node.js${{matrix.node-version }}
            - uses: actions/setup-node@v2
              with:
                node-version: ${{matrix.node-version }}
            - name: Install Dependencies
              -run: npm ci
              run: npm run build --if-present
            - name: npm test
            
              run: npm run cy:run
            - name: Publish Report
              uses: peaceiris/actions-gh-pages@v3
              if: always()
              with:
                github_token: ${{secrets.GITHUB_TOKEN}}
                publish_dir: ./alure-repot
uses: peaceiris/actions-gh-pages@v3
  with:
  github_token: ${{ secrets.GITHUB_TOKEN }}
     publish_dir: ./mochawesome-report


